### ISSUE TITLE
Rethinking the way we go about things

### ISSUE THREAD

**Issue by Maxqia** [disks86/VK9#12]
> Test & Implement functionality required for “Using the Attributes Table of D3DXMesh to Render Sub-sets” sample. (Target 1-2020)

..., I don't think there'll be a need for this project in 2020, because by then, most new games will use DX12/Vulkan and Wine will have a full implementation of DX11 and maybe DX12. Therefore, I propose a new way of doing things. 
    The Wine developers main concerns with allowing the Gallium Nine code into Wine is that it wouldn't replace any of the existing code, because they would still need to support OpenGL for Mac users. This could be solved by porting Gallium3D to Mac (and Windows I guess) via Vulkan. According to the Mesa devs, Vulkan is slightly lower level than Gallium3D is, so it should be possible, and it should be less work than translating Vulkan to DX9. Gallium3D already has support for DX9, and experimental (deserted) support for DX1X. (Also, it would support OpenGL 4.4 on a Mac!)

I'd do it if I knew the first thing about graphics, Idea from [this] (https://www.reddit.com/r/vulkan/comments/3q1i4o/implementing_gl_on_vulkan_using_a_gallium3d_pipe/) reddit post, which is 3 search results up from where I found this project while searching for "vulkan gallium3d" :P

**Comment by AsuMagic** [comment]
I'm not sure if I understood it well, but I think I kind of miss the point. What do you really mean? Would that allow using Gallium Nine for example on proprietary nvidia drivers or on OSX?

**Comment by Maxqia** [comment]
Yeah (When Apple finally gives up Metal and Supports Vulkan :P), I'm mainly proposing an easier way to implement d3d on Vulkan, to summarize.

**Comment by AsuMagic** [comment]
But Apple said they won't support Vulkan. And I don't think that will be a reason for Wine devs to implement Gallium Nine directly. After all that's not a truly multiplatform solution. That being said, the Gallium Nine patch for Wine is doing very well and can be installed on most distros with a user repository (it was extremely easy to install on my Arch laptop - a simple yaourt setup and a box to tick in winecfg).

Now I wonder : Is it worth it for OSX? Because I think a DX9 <- Gallium nine -> Vulkan <- MoltenVK -> Metal bridge still, I think, have a performance cost. Now if that's faster than wined3d, and it probably would be if done correctly, that's a good thing to have.

This would also have a positive (or negative? promoting open technologies is what will push alternative platforms to Windows forwards, but gamers for example are lacking the game compatibility and performance they had from Windows) effect in the Linux world : We could start using Gallium Nine with nvidia proprietary drivers and AMD proprietary drivers (even if their open drivers are starting to match their closed ones).

There's also a major advantage I see to it: This could help promoting the Gallium Nine project and, who knows, maybe even make the D3D11 wrapper live up again.

I wonder what disks86 thinks about it.

If I find up some way to contribute in my level of knowledge (understand : medium C++ knowledge and ~0 graphics knowledge), I'll be there to help.

**Comment by disks86** [comment]
I agree 2020 is pretty far out but that is a current estimate based on how long it's taking me to get through these by myself. If more folks get involved it could be sooner. That said people are still making games with D3d9 Tree of Savior is an example of this. The thing is that d3d9 is well documented and there are piles of code out there for people to work with. Time could prove me wrong but I believe that saying d3d9 will be gone in 4 years is like saying America will be using metric in 4 years.

I think we need to be careful about stacking wrappers though even wrapping the WSI extensions has some overhead as seen by benchmarks for Talos Principle under Wine with Vulkan. Also I would love to see Apple bring Vulkan to OSX and IOS however I'm taking the wait and see approach on that one.

One last thing to keep in mind. With the approach I'm taking I can test the library on Windows. This means I can take all other sources of wrapper overhead out of the picture. This also means I can test without worrying about Wine bugs. All I have to do for unit testing is drop the DLL and associated files in the sample folder and run the sample.

**Comment by Maxqia** [comment]
With my approach I'm saying write a Vulkan->Gallium3D layer and test it using the unit tests for Gallium3D itself, no having to deal with Wine (and it's bugs) at all. Also Linux driver developers no longer have to support Vulkan and Gallium3D as they currently have to do now.

**Comment by disks86** [comment]
You'll still have to use Wine to test any real d3d applications. It's an interesting idea but I don't think it's a good fit for what I'm trying to do.

**Comment by Maxqia** [comment]
No, you can compile Mesa + Gallium Nine (probably with a few hacks) for Windows, and it's already happening with wined3d [here](http://adolfintel.com/?p=wined3d/index.frag). From what I can tell, DX9 should already work, although slow, with the llvm-pipe (cpu) driver.

**Comment by disks86** [comment]
I was not aware of that project. One of the benefits of this project however is that it will provide a mapping between DirectX9 (which has high adoption) to Vulkan. I would be interested to see someone attempt what you're suggesting but it's not in line with my goals.

**Comment by axeldavy** [comment]
I'd like to add a bit more information to the suggestions of this thread.
Mesa is the open source linux GL driver for all graphic cards (though support is not very good for nvidia. It is good for the others).

Internally most drivers use an internal abstraction: gallium.
GL maps to gallium calls (we call that the GL "state tracker"), and drivers implement the gallium API.
The gallium API was initially designed to be close to dx10, and evolved since.

I think implementing a gallium driver translating gallium API to Vulkan calls would be much easier than this current project because:
-> Gallium nine could be used directly for the dx9 implementation
    . Thus all corner cases implemented
    . All error checking already there
    . Internal Multithreading and thread safety implemented
    . Format conversion code implemented by gallium utils (gallium drivers and state trackers have access to a use utils library, which is very useful to implement a lot of features).
-> You get GL implementation on top of Vulkan at the same time (and possibly dx11 if ever someone adds a new state tracker for it).
-> The API to implement is shorter and easier to implement than dx9
    . The gallium API is shorter, less complex, and doesn't need error checking (only calls in the spec are made by the state trackers)
    . The utils libraries make it easier to implement a driver.

Currently you can get a GL driver on windows with mesa using the llvmpipe gallium driver (which draws with cpu). The other drivers talk to the linux kernel for rendering and thus are not compatible, but that wouldn't be an issue with Vulkan. Gallium nine would need small modifications to work on windows with Vulkan, but if you're willing to do a Vulkan state trackers, Gallium nine devs will help there.

If you decide to go for that route, I don't think you have lost time. You have learnt the Vulkan API well and what you wrote could be likely partially reusable for writing the gallium vulkan translation. However you'd achieve your goals much faster.


Links to documentation to the gallium API (which the gallium driver talking to Vulkan would have to implement):
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/include/pipe/p_screen.h
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/include/pipe/p_context.h
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/docs/source/screen.rst
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/docs/source/tgsi.rst
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/docs/source/context.rst

**Comment by disks86** [comment]
I am currently focusing on VK9 however I think the idea of Gallium over Vulkan is worth exploring. I setup a VKG channel on the new discord server which those of you interested in this alternative approach can use to coordinate. https://discord.gg/EMc4Kak
