### ISSUE TITLE
[Question] Milestone 23: Should "post processing" effects support be added now? Or after all set milestones are complete?

### ISSUE THREAD

**Issue by Weej1** [disks86/VK9#22]
Hi!
I've been quietly lurking and keep tabs on your progress for quite sometime now! Love what you're doing and agree with your reasons for doing them too! I saw that you'd recently reached your 23rd milestone that deals with implementing HLSL support. 

That got me thinking about "post processing injectors". You may have heard of the popular one called ENB which is really a heavily modified `direct3d.dll` (and the like). The other popular option is [ReShade](https://reshade.me/) which is open source. Both rely on shaders and I was wondering now that you've reached this milestone, Would one be able to use these injectors as drop-ins along with vk9? Or is it a case of you restructuring your code so that support for connecting these effects processors is available in the future? (Or perhaps even re-implementing these to fit into VK9)?

btw my apologies if this isn't the right place to ask this question. I didn't know where else to ask you. Anyhow Happy holidays and New Year!

**Comment by Nucleoprotein** [comment]
Milestone 23 is very very -very- basic shared support, it can't run games yet and I think it will not run them very soon, maybe in 2019?

**Comment by disks86** [comment]
As Nucleoprotein pointed out VK9 can't yet run games. My understanding is that those "injectors" work by implementing the D3D.dll file. If that is the case it would be a one or the other scenario. However the license on VK9 is very liberal so someone could combine them if the license of the other project allows it. I don't intend to directly support those types of efforts primarily because I still have plenty of work to do on the core project.
